global:
    kolla:
        all:
            kubernetes_entrypoint: true
        ironic:
            api:
                deployment:
                    dependencies:
                        jobs:
                        - ironic-create-keystone-endpoint-public
                        - ironic-create-keystone-endpoint-internal
                        - ironic-create-keystone-endpoint-admin
                        - ironic-create-db
                        - ironic-manage-db
                        service:
                        - mariadb
                        - keystone-admin
                svc:
                    port_external: true
                create_db:
                    job:
                        dependencies:
                            service:
                            - mariadb
                manage_db:
                    job:
                        dependencies:
                            service:
                            - mariadb
                            jobs:
                            - ironic-create-db
                create_keystone_endpoint:
                    public:
                        job:
                            dependencies:
                                jobs:
                                - ironic-create-keystone-service
                                - ironic-create-keystone-user
                                - ironic-create-keystone-endpoint-internal
                                - ironic-create-keystone-endpoint-admin
                                service:
                                - keystone-admin
                    internal:
                        job:
                            dependencies:
                                jobs:
                                - ironic-create-keystone-service
                                - ironic-create-keystone-user
                                - ironic-create-keystone-endpoint-admin
                                service:
                                - keystone-admin
                    admin:
                        job:
                            dependencies:
                                jobs:
                                - ironic-create-keystone-service
                                - ironic-create-keystone-user
                                service:
                                - keystone-admin
            create_keystone_user:
                job:
                    dependencies:
                        jobs:
                        - ironic-create-keystone-service
                        service:
                        - keystone-admin
            create_keystone_service:
                job:
                    dependencies:
                        service:
                        - keystone-admin
            conductor:
                daemonset:
                    dependencies:
                        service:
                        - mariadb
                        - keystone-admin
                        - ironic-api
