global:
    kolla:
        all:
            kubernetes_entrypoint: true
            type: network
        openvswitch:
            vswitchd:
                all:
                    dependencies:
                        socket:
                        - /var/run/openvswitch/db.sock
