global:
    kolla:
        all:
            kubernetes_entrypoint: true
        neutron:
            delete_db:
                job:
                    dependencies:
                        service:
                        - mariadb
            delete_keystone_user:
                job:
                    dependencies:
                        service:
                        - keystone-admin
            delete_keystone_service:
                job:
                    dependencies:
                        service:
                        - keystone-admin
