{{- $searchPath := ":global.kolla.neutron.delete_db.job:global.kolla.neutron.delete_db.all:global.kolla.neutron.server.all:global.kolla.neutron.all:global.kolla.all" }}
{{- $resourceName := "neutron" }}
{{- $serviceName := "neutron" }}
{{- $podTypeBootstrap := true }}
{{- with $env := dict "resourceName" $resourceName "serviceName" $serviceName "podTypeBootstrap" $podTypeBootstrap "Values" .Values "Release" .Release "searchPath" $searchPath }}
{{- include "common_delete_db_job" $env }}
{{- end }}
